package com.example.rabbittask.model

data class HotSpot(
    val address: String,
    val arabic_description: String,
    val arabic_name: String,
    val arabic_short_description: Any,
    val categories: List<CategoryX>,
    val city: CityXX,
    val city_id: CityId,
    val cuisineTypes: List<CuisineType>,
    val description: String,
    val external_rating: List<Any>,
    val facebook: String,
    val facebook_id: Any,
    val facebook_image: Any,
    val features: List<FeatureX>,
    val id: Int,
    val instagram: String,
    val lat: String,
    val lng: String,
    val menus: List<String>,
    val name: String,
    val neighborhood: Neighborhood,
    val offers: List<Any>,
    val phone: String,
    val photos: List<String>,
    val price_of_two: String,
    val profile_photo: String,
    val short_description: String,
    val twitter: Any,
    val video: Any,
    val views: Int,
    val website: String
)